### PR TITLE
updated footer section

### PR DESCRIPTION
**Pull request by Janhvi52**
before
Screenshot (112)

after
Screenshot (113)

hope you like it!

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
> before Screenshot (112)
> 
> after Screenshot (113)
> 
> hope you like it!

@Janhvi52 try to make it more attractive

**Comment by Riya14-dangra** [comment]
It just seems me to change in color try to make more attractive changes

**Comment by Riya14-dangra** [comment]
It just seems me to change in color try to make more attractive changes

**Comment by Janhvi52** [comment]
> It just seems me to change in color try to make more attractive changes

you can check now
i've added linear gradient to the footer section that complements the color of the webpage!

**Comment by Riya14-dangra** [comment]
> > It just seems me to change in color try to make more attractive changes
> 
> you can check now i've added linear gradient to the footer section that complements the color of the webpage!

Share the snapshot of it

**Comment by Janhvi52** [comment]
> > > It just seems me to change in color try to make more attractive changes
> > 
> > 
> > you can check now i've added linear gradient to the footer section that complements the color of the webpage!
> 
> Share the snapshot of it

Screenshot (114)

can check now!

**Comment by Riya14-dangra** [comment]
@Janhvi52 Unable to see 👀

**Comment by Janhvi52** [comment]
> @Janhvi52 Unable to see 👀

mb, it's still uploading(network issues)

**Comment by Janhvi52** [comment]
> @Janhvi52 Unable to see 👀

you can see now
sorry for the inconvenience

**Comment by Riya14-dangra** [comment]
> > @Janhvi52 Unable to see 👀
> 
> you can see now sorry for the inconvenience

Change the linear gradient color make it according to the theme of website

**Comment by Janhvi52** [comment]
> > > @Janhvi52 Unable to see 👀
> > 
> > 
> > you can see now sorry for the inconvenience
> 
> Change the linear gradient color make it according to the theme of website

can you tell me in which color u want, i already tried so many permutations and combinations
it would be better if you'll guide once

**Comment by Janhvi52** [comment]
> > > @Janhvi52 Unable to see 👀
> > 
> > 
> > you can see now sorry for the inconvenience
> 
> Change the linear gradient color make it according to the theme of website

Screenshot (122)

i've made it in accordance to the theme of website
hope u like it now!

**Comment by Riya14-dangra** [comment]
Add more contact info

**Comment by Janhvi52** [comment]
> Add more contact info

Screenshot (123)

hope you like it now!

**Comment by Janhvi52** [comment]
> Add more contact info



> Add more contact info

Screenshot (126)

hope u like it now!

**Comment by Riya14-dangra** [comment]
Design it in such a way that it looks more attractive not simpler as now

**Comment by Janhvi52** [comment]
> Design it in such a way that it looks more attractive not simpler as now

it was better before the last commit ig, was more fascinating already and with white and black as background nothing much can be done
any changes you recommend on your part?

**Comment by Riya14-dangra** [comment]
Try to make the follow us section in footer horizontally

**Comment by Janhvi52** [comment]
> Try to make the follow us section in footer horizontally

Screenshot (129)

hope u'll like it now!

**Comment by Riya14-dangra** [comment]
Resolve the conflict

**Comment by Janhvi52** [comment]
> Resolve the conflict

can see now!

**Comment by Riya14-dangra** [comment]
Follow us wale section ko sab se niche move karo aur thoda attractive banaao n vo bohat broad lagra aur itna attractive nhi lagra

**Comment by Janhvi52** [comment]
> Follow us wale section ko sab se niche move karo aur thoda attractive banaao n vo bohat broad lagra aur itna attractive nhi lagra

follow us to hmesa copyrights ke upr hi rheta na ofc?

**Comment by Riya14-dangra** [comment]
Resolve the conflict

**Comment by Riya14-dangra** [comment]
> > Follow us wale section ko sab se niche move karo aur thoda attractive banaao n vo bohat broad lagra aur itna attractive nhi lagra
> 
> follow us to hmesa copyrights ke upr hi rheta na ofc?

Copyright hata do vo sab footer me add karo sab se last me

**Comment by Janhvi52** [comment]
> > > Follow us wale section ko sab se niche move karo aur thoda attractive banaao n vo bohat broad lagra aur itna attractive nhi lagra
> > 
> > 
> > follow us to hmesa copyrights ke upr hi rheta na ofc?
> 
> Copyright hata do vo sab footer me add karo sab se last me

Screenshot (135)

now it is as per your request and attractive as well,at least different from tradition things
hope its fine now

**Comment by Janhvi52** [comment]
> > > > Follow us wale section ko sab se niche move karo aur thoda attractive banaao n vo bohat broad lagra aur itna attractive nhi lagra
> > > 
> > > 
> > > follow us to hmesa copyrights ke upr hi rheta na ofc?
> > 
> > 
> > Copyright hata do vo sab footer me add karo sab se last me
> 
> Screenshot (135)
> 
> now it is as per your request and attractive as well,at least different from tradition things hope its fine now

hey riya,kindly review it and merge it
i need to include this pr in my blog which i'm writing for kwoc
if u want any further changes i'll make other pr for that
thankyou!

**Comment by Riya14-dangra** [comment]
Sorry I can't able to merge it . It not seems (not design according to requirement)good to me.

**Comment by Janhvi52** [comment]
> Sorry I can't able to merge it . It not seems good to me. 

specify the desired changes bruh, I'll do it
You aren't specifying properly what are your requirements, everytime u come up with new ones , how it'll work :) 
Please specify em one more time what all you need in footer section with what kind of background n all, I'll do changes accordingly

**Comment by Riya14-dangra** [comment]
Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.

**Comment by Janhvi52** [comment]
> Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.

Screenshot (136)

have a look at the new design
this is so different from the traditional ones and attractive too since it is out of the box
hope u like it now !

**Comment by Janhvi52** [comment]
> > Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.
> 
> Screenshot (136)
> 
> have a look at the new design this is so different from the traditional ones and attractive too since it is out of the box hope u like it now !

you there?

**Comment by Riya14-dangra** [comment]
It seems same as before try to modify it more

**Comment by Riya14-dangra** [comment]
> > > Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.
> > 
> > 
> > Screenshot (136)
> > have a look at the new design this is so different from the traditional ones and attractive too since it is out of the box hope u like it now !
> 
> you there?

Yes I am here but I am busy in my practical exams

**Comment by Janhvi52** [comment]
> > > > Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.
> > > 
> > > 
> > > Screenshot (136)
> > > have a look at the new design this is so different from the traditional ones and attractive too since it is out of the box hope u like it now !
> > 
> > 
> > you there?
> 
> Yes I am here but I am busy in my practical exams

kindly review my pr once!

**Comment by Janhvi52** [comment]
> > > > > Design the footer in such a way that it looks attractive, color of footer is matched to the theme of website and it seems different and more attractive than all others website footer.
> > > > 
> > > > 
> > > > Screenshot (136)
> > > > have a look at the new design this is so different from the traditional ones and attractive too since it is out of the box hope u like it now !
> > > 
> > > 
> > > you there?
> > 
> > 
> > Yes I am here but I am busy in my practical exams
> 
> kindly review my pr once!

it'll just take few mins of yours :)

**Comment by Riya14-dangra** [comment]
It really can't looks good to me in designing as it look much better in before

**Comment by Janhvi52** [comment]
> It really can't looks good to me in designing as it look much better in before

okay ma'am!

**Pull request closed without merging**
