### PR TITLE
Merge pull request #1 from Riya14-dangra/master

### PR DESCRIPTION
**Pull request by likhithaindukuri**
I modified the header section.

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
> I modified the header section.

@likhithaindukuri can you share the snapshot of your work

**Comment by likhithaindukuri** [comment]
> > I modified the header section.
> 
> @likhithaindukuri can you share the snapshot of your work

I didn't get you.

**Comment by Riya14-dangra** [comment]
> > > I modified the header section.
> > 
> > 
> > @likhithaindukuri can you share the snapshot of your work
> 
> I didn't get you.

share the photo of the output work that you done

**Comment by likhithaindukuri** [comment]
Hey Riya! when we will get a certification for the contributions in kwoc?

**Pull request merged**
